### ISSUE TITLE
a=routine_info(/so) crashes gdl (+ implement it!)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#196]
```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007fffef0c8e7b in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fffef0ca231 in __GI_abort () at abort.c:79
#2  0x00007fffef0c19da in __assert_fail_base (fmt=0x7fffef214d48 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff79b61a8 "d0 != 0", file=file@entry=0x7ffff79b6b20 "/build/gnudatalanguage-nJX6mN/gnudatalanguage-0.9.8/src/dimension.hpp", line=line@entry=79, function=function@entry=0x7ffff79f2610 <_ZZN9dimensionC4EyE19__PRETTY_FUNCTION__> "dimension::dimension(SizeT)") at assert.c:92
#3  0x00007fffef0c1a52 in __GI___assert_fail (assertion=assertion@entry=0x7ffff79b61a8 "d0 != 0", file=file@entry=0x7ffff79b6b20 "/build/gnudatalanguage-nJX6mN/gnudatalanguage-0.9.8/src/dimension.hpp", line=line@entry=79, function=function@entry=0x7ffff79f2610 <_ZZN9dimensionC4EyE19__PRETTY_FUNCTION__> "dimension::dimension(SizeT)") at assert.c:101
#4  0x00007ffff75f02f1 in lib::routine_info(EnvT*) (d0=<optimized out>, this=<optimized out>) at ./src/dimension.hpp:79
#5  0x00007ffff75f02f1 in lib::routine_info(EnvT*) (e=<optimized out>) at ./src/basic_fun.cpp:7193
#6  0x00007ffff792e263 in FCALL_LIB_RETNEWNode::Eval() (this=0x555555a5cbe0) at ./src/prognodeexpr.cpp:3158
#7  0x00007ffff791f7c4 in ASSIGN_REPLACENode::Run() (this=0x555555a5cb30) at ./src/prognode.cpp:913
#8  0x00007ffff70ad01b in GDLInterpreter::statement(ProgNode*) (this=this@entry=0x7fffffffe060, _t=<optimized out>) at ./src/GDLInterpreter.cpp:96
#9  0x00007ffff70adef8 in GDLInterpreter::interactive(ProgNode*) (this=this@entry=0x7fffffffe060, _t=<optimized out>, _t@entry=0x555555a5cb30)
    at ./src/GDLInterpreter.cpp:39
#10 0x00007ffff76488bd in DInterpreter::ExecuteLine(std::istream*, unsigned long long) (this=this@entry=0x7fffffffe060, in=in@entry=0x0, lineOffset=lineOffset@entry=0) at ./src/dinterpreter.cpp:1238
#11 0x00007ffff764ba00 in DInterpreter::InterpreterLoop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x7fffffffe060, startup="", batch_files=..., statement=...) at ./src/dinterpreter.cpp:1741
#12 0x000055555555bcb8 in main(int, char**) (argc=1, argv=0x7fffffffe388) at ./src/gdl.cpp:414
```

**Comment by GillesDuvert** [comment]
works for me...
OS dependency?

**Comment by slayoo** [comment]
Let's see - added a test routine: https://github.com/gnudatalanguage/gdl/pull/235

**Comment by slayoo** [comment]
Also, as per @swensonator's and @acoulais's reports on SF.net (https://sourceforge.net/p/gnudatalanguage/bugs/540/) the /SOURCE kw functionality is not implemented for the case of no positional argument.

**Comment by slayoo** [comment]
The added test failed all 6 builds on travis, see e.g.: https://travis-ci.org/gnudatalanguage/gdl/jobs/368986073#L6361

```
% Compiled module: TEST_GH00196.
gdl: /home/travis/build/gnudatalanguage/gdl/src/dimension.hpp:79: dimension::dimension(unsigned long long): Assertion `d0 != 0' failed.
```
