### ISSUE TITLE
!NULL-related segfault 

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#221]
As reported by @maynardGK on SF.net (https://sourceforge.net/p/gnudatalanguage/bugs/698/):

```
GDL> tt=[ ]
GDL> p=ptr_new(tt)
GDL> tstcmp=lonarr(3,3,4)
GDL> i=where(tstcmp ne *p,nc)
gdl: /build/gnudatalanguage-nJX6mN/gnudatalanguage-0.9.8/src/prognodeexpr.cpp:340: void BinaryExprNC::AdjustTypesNCNull(Guard<BaseGDL>&, BaseGDL*&, Guard<BaseGDL>&, BaseGDL*&): Assertion `false' failed.
Aborted
```

```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007fffef0c8e7b in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fffef0ca231 in __GI_abort () at abort.c:79
#2  0x00007fffef0c19da in __assert_fail_base (fmt=0x7fffef214d48 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff79aec6b "false", file=file@entry=0x7ffff7a59918 "/build/gnudatalanguage-nJX6mN/gnudatalanguage-0.9.8/src/prognodeexpr.cpp", line=line@entry=340, function=function@entry=0x7ffff7a5a200 <BinaryExprNC::AdjustTypesNCNull(Guard<BaseGDL>&, BaseGDL*&, Guard<BaseGDL>&, BaseGDL*&)::__PRETTY_FUNCTION__> "void BinaryExprNC::AdjustTypesNCNull(Guard<BaseGDL>&, BaseGDL*&, Guard<BaseGDL>&, BaseGDL*&)") at assert.c:92
#3  0x00007fffef0c1a52 in __GI___assert_fail (assertion=assertion@entry=0x7ffff79aec6b "false", file=file@entry=0x7ffff7a59918 "/build/gnudatalanguage-nJX6mN/gnudatalanguage-0.9.8/src/prognodeexpr.cpp", line=line@entry=340, function=function@entry=0x7ffff7a5a200 <BinaryExprNC::AdjustTypesNCNull(Guard<BaseGDL>&, BaseGDL*&, Guard<BaseGDL>&, BaseGDL*&)::__PRETTY_FUNCTION__> "void BinaryExprNC::AdjustTypesNCNull(Guard<BaseGDL>&, BaseGDL*&, Guard<BaseGDL>&, BaseGDL*&)") at assert.c:101
#4  0x00007ffff7933291 in BinaryExprNC::AdjustTypesNCNull(Guard<BaseGDL>&, BaseGDL*&, Guard<BaseGDL>&, BaseGDL*&) (this=0x555555790040, g1=..., e1=@0x7fffffffd5f8: 0x5555559342f0, g2=..., e2=@0x7fffffffd600: 0x0) at ./src/prognodeexpr.cpp:340
#5  0x00007ffff7933400 in NE_OPNCNode::Eval() (this=<optimized out>) at ./src/prognodeexpr.cpp:1632
#6  0x00007ffff791fb66 in ParameterNode::Parameter(EnvBaseT*) (this=0x555555a5cdd0, actEnv=0x555555a5e280) at ./src/prognode.cpp:777
#7  0x00007ffff70ab979 in GDLInterpreter::parameter_def_nocheck(ProgNode*, EnvBaseT*) (this=0x7fffffffe060, _t=<optimized out>, actEnv=actEnv@entry=0x555555a5e280) at ./src/GDLInterpreter.cpp:3363
#8  0x00007ffff792e25d in FCALL_LIB_RETNEWNode::Eval() (this=0x555555a5ce80) at ./src/prognodeexpr.cpp:3154
#9  0x00007ffff791f7c4 in ASSIGN_REPLACENode::Run() (this=0x555555a7a830) at ./src/prognode.cpp:913
#10 0x00007ffff70ad01b in GDLInterpreter::statement(ProgNode*) (this=this@entry=0x7fffffffe060, _t=<optimized out>) at ./src/GDLInterpreter.cpp:96
#11 0x00007ffff70adef8 in GDLInterpreter::interactive(ProgNode*) (this=this@entry=0x7fffffffe060, _t=<optimized out>, _t@entry=0x555555a7a830)
    at ./src/GDLInterpreter.cpp:39
#12 0x00007ffff76488bd in DInterpreter::ExecuteLine(std::istream*, unsigned long long) (this=this@entry=0x7fffffffe060, in=in@entry=0x0, lineOffset=lineOffset@entry=0) at ./src/dinterpreter.cpp:1238
#13 0x00007ffff764ba3a in DInterpreter::InterpreterLoop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x7fffffffe060, startup="", batch_files=..., statement=...) at ./src/dinterpreter.cpp:1741
#14 0x000055555555bcb8 in main(int, char**) (argc=1, argv=0x7fffffffe388) at ./src/gdl.cpp:414
```

**Comment by GillesDuvert** [comment]
closed by #1174
