### ISSUE TITLE
Crash reading 2D idlsave file with scipy.io.idl's readsav created by GDL but not by IDL

### ISSUE THREAD

**Issue by zoglauer** [gnudatalanguage/gdl#575]
I get a crash when I try to read a 2D double array's stored in an idlsave file using scipy.io.idl's readsav - but only when the file is created by GDL, not when it is created by IDL

### Reproducing code example:
To create the idl save file with GDL:
```
S=DBLARR(3)
SAVE,S,FILENAME="NoBug1D.idlsave"

D=DBLARR(3,3)
SAVE,D,FILENAME="Bug2D.idlsave"
```
As the output file names suggest, the 1D array in "NoBug1D.idlsave" can be read correctly, th2 2D array in "Bug2D.idlsave" will crash.

You can simply read those files with python via:
```
from scipy.io.idl import readsav
s = readsav("NoBug1D.idlsave",verbose=True)
d = readsav("Bug2D.idlsave",verbose=True)
```

### Error message:
```
>>> from scipy.io.idl import readsav
>>> s = readsav("NoBug1D.idlsave",verbose=True)
--------------------------------------------------
Date: Fri Feb 22 11:58:15 2019
User: andreas
Host: thetis
--------------------------------------------------
Format: 5
Architecture: x86_64
Operating System: linux
IDL Version: 6.5
--------------------------------------------------
Successfully read 4 records of which:
 - 1 are of type VERSION
 - 1 are of type VARIABLE
 - 1 are of type TIMESTAMP
--------------------------------------------------
Available variables:
 - s [<class 'numpy.ndarray'>]
--------------------------------------------------
>>> d = readsav("Bug2D.idlsave",verbose=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andreas/Home/Science/Software/ChargeTransport/IDLCode/idlsave/python-env/lib/python3.6/site-packages/scipy/io/idl.py", line 801, in readsav
    r = _read_record(f)
  File "/home/andreas/Home/Science/Software/ChargeTransport/IDLCode/idlsave/python-env/lib/python3.6/site-packages/scipy/io/idl.py", line 362, in _read_record
    rectypedesc['array_desc'])
  File "/home/andreas/Home/Science/Software/ChargeTransport/IDLCode/idlsave/python-env/lib/python3.6/site-packages/scipy/io/idl.py", line 311, in _read_array
    array = array.reshape(dims)
ValueError: cannot reshape array of size 2 into shape (3,3)
>>> 
```

When I try the same with IDL, everything is fine.

### Scipy/Numpy/Python version information:
```
GDL: 0.9.9
Scipy: 1.2.1 
Numpy: 1.16.1
Python: 3.6
```

**Comment by alaingdl** [comment]
Hi, thanks for the feedback. I cannot reproduce you bug, but I am far from your configuration

Hum, which version of GDL are you using ?
```
GDL> !gdl
{ 0.9.9 git Feb 16 2019  1550271600   0   0 CRUDE}
```

```
In [5]: d = readsav("Bug2D.idlsave",verbose=True)
--------------------------------------------------
Date: Fri Feb 22 21:35:14 2019
User: alain
Host: planck4
--------------------------------------------------
Format: 9
Architecture: x86_64
Operating System: linux
IDL Version: 8.2
--------------------------------------------------
Successfully read 4 records of which:
 - 1 are of type VARIABLE
 - 1 are of type TIMESTAMP
 - 1 are of type VERSION
--------------------------------------------------
Available variables:
 - d [<type 'numpy.ndarray'>]
--------------------------------------------------

In [6]: d
Out[6]: 
{'d': array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])}

```

**Comment by zoglauer** [comment]
I was using the GDL version from Ubuntu 18.04 - the latest version in git does not have the issue!
Closing the issue.
